### ISSUE TITLE
Error in npx installable-framer 

### ISSUE THREAD

**Issue by EkaterinaMolchanova** [remorses/installable-framer#1]
Hi Tommy, 

I think your product is great and really want to try it out but I'm getting an error at step 4 of READme.md while running "npx installable-framer" command: 

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'classnames' imported from /Users/.../pipeline/node_modules/installable-framer/dist/react.js

Link to my component: https://framer.com/m/Item-Qetw.js@vUDyI0yvPLONiBDf8Kzw

I've tried a couple of other components just in case - the same error.

Could you please have a look into this?

Thank you and regards, 
Kate

**Comment by remorses** [comment]
Thank you for the report!, fixed in latest version

**Comment by EkaterinaMolchanova** [comment]
Works for me as well. Thank you so much for your prompt response!
